name: marketapp
description: A new Flutter project.

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  app_version: ^0.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  flutter_riverpod: ^2.3.2
  path_provider: ^2.0.14
  http: ^0.13.6
  sqflite: ^2.2.8+4
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: BalooBhai
      fonts:
        - asset: assets/fonts/BalooBhai.ttf

    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf  

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf      
  
  uses-material-design: true

      