// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpnTuzt5WyRK8rqsgpkpLNg3pPBw9ZODk',
    appId: '1:311081909770:web:57f60aca5d60031b3969f3',
    messagingSenderId: '311081909770',
    projectId: 'marketapp-b344e',
    authDomain: 'marketapp-b344e.firebaseapp.com',
    storageBucket: 'marketapp-b344e.appspot.com',
    measurementId: 'G-HEEF4FG2BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmcgulaFKRK3--UiN-3RJhgoXMhxWZmPI',
    appId: '1:311081909770:android:21ec2db72e3852f13969f3',
    messagingSenderId: '311081909770',
    projectId: 'marketapp-b344e',
    storageBucket: 'marketapp-b344e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzcCpieIDRKAbtYfteg5hkiKS1Q3Ff5U',
    appId: '1:311081909770:ios:3e083ebb29e19aff3969f3',
    messagingSenderId: '311081909770',
    projectId: 'marketapp-b344e',
    storageBucket: 'marketapp-b344e.appspot.com',
    iosClientId: '311081909770-mjc4bpb6dfve4nts9ejls55jq1hd35nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketapp',
  );
}
