List products = [
  {
    "id": "1",
    "category_name": "Teknoloji",
    "name": "Apple Usb Güç Adaptörü",
    "property": "12 W",
    "price": "429.10",
    "img": "assets/images/adaptor.jpg",
    "details": [
      "Bu kompakt güç adaptörü, aygıtlarınızı evde ofiste veya yolda hızlı ve verimli bir şekilde şarj edebilmenizi sağlar.",
      "tüm Apple watch, iPhone veya iPod modelleriyle çalışır.",
      "Apple Türkiye garantilidir.",
    ]
  },
  {
    "id": "2",
    "category_name": "icecek",
    "name": "Dimes Meyvesuyu",
    "property": "kayısılı, 1L",
    "price": "22.99",
    "img": "assets/images/meyvesuyu.jpg",
    "details": [],
  },
  {
    "id": "3",
    "category_name": "icecek",
    "name": "maden suyu",
    "property": "200 ml",
    "price": "5.99",
    "img": "assets/images/soda.jpg",
    "details": [],
  },
  {
    "id": "4",
    "category_name": "temizlik",
    "name": "Pril bulaşık deterjanı",
    "property": "4 L",
    "price": "125.99",
    "img": "assets/images/deterjan.jpg",
    "details": [],
  },
  {
    "id": "5",
    "category_name": "meyve",
    "name": "elma",
    "property": "1 kg",
    "price": "15.99",
    "img": "assets/images/elma.jpg",
    "details": [],
  },
  {
    "id": "6",
    "category_name": "Teknoloji",
    "name": "Samsung Galaxy S20",
    "property": "Android, Beyaz",
    "price": "100.99",
    "img": "assets/images/samsung.jpg",
    "details": [],
  },
  {
    "id": "7",
    "category_name": "Teknoloji",
    "name": "Samsung Galaxy S20",
    "property": "Android, Beyaz",
    "price": "3359.99",
    "img": "assets/images/samsung.jpg",
    "details": [],
  },
];
